#!/bin/bash

# Download parallel package as dependency
sudo apt install parallel -y

# Check arguments
if [ $# -eq 0 ]
  then
    printf "No arguments supplied. Please supply a valid IP address or addresses to scan\nExample: initial-enum 192.168.12.201\ninitial-enum 192.168.12.34 192.168.12.101"
    
    exit
fi


# Colors
GREEN="\e[32m"
BLUE="\e[34m"
ENDCOLOR="\e[0m"
SUCCESS="${GREEN}[+]${ENDCOLOR}"
INFO="${BLUE}[*]${ENDCOLOR}"

for ip in "$@"
do
	# Run nmap top 100 UDP scan first
	printf "$SUCCESS Performing UDP Scans with Nmap...\n"
	sudo nmap -T5 -sU -sV --top-ports=100 $ip -v | tee nmap-udp-top-100-$ip.txt
	sudo nmap -T5 -sU -sV --top-ports=10 $ip -v | tee nmap-udp-top-10-$ip.txt 
	
	# Function that performs enumeration
	printf "$SUCCESS Scanning $ip with Nmap...\n" 
	ports=$(sudo nmap -Pn -T5 -p- $ip -v | grep Discovered | awk -F " " '{print substr($4,1,length($4)-4)}')
	echo $ports > tcp-ports-$ip
	
	
	
	printf "$SUCCESS Ports found by nmap:\n"
	for port in `echo $ports`
	do
		printf "$INFO $port\n"
	done
	
	printf "$PLUS Running autorecon now...\n"
	autorecon $ip -p $(echo $ports | tr ' ' ',') --dirbuster.wordlist /usr/share/wordlists/seclists/Discovery/Web-Content/common.txt /usr/share/wordlists/seclists/Discovery/Web-Content/raft-large-files.txt /usr/share/wordlists/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt &; fg
done

for ip in "$@"
do
	
done
